services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: gstaudit-backend:latest
    container_name: gstaudit-backend
    ports:
      - "8001:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: gstaudit-frontend:latest
    container_name: gstaudit-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: unless-stopped
